### ISSUE TITLE
Question: How to add livy chart as dependent chart

### ISSUE THREAD

**Issue by manjiler** [jahstreet/spark-on-kubernetes-helm#65] opened 2021-05-08 12:07 UTC
First off - amazing work get this helm chart!!!

I tried specifying the dependencies 
```
dependencies:
- name: livy
  version: "v2.0.2"
  repository: https://jahstreet.github.io/helm-charts

```

It does not work. 
I might be doing something wrong here. 

What is correct way to add livy chart as a dependencies?

**Comment by manjiler** [comment] 2021-05-09 10:41
For now I am manually copied helm chart for livy and added it under charts folder. 
Let me if there is better way to do it.

**Comment by jahstreet** [comment] 2021-05-14 08:37
Hi @manjiler , thx for the feedback. Can you share the errors you observe?

**Comment by manjiler** [comment] 2021-05-14 09:15
After adding livy as dependency in Chart.yaml. Running helm dependency update, give the below error
`
Error: can't get a valid version for repositories livy. Try changing the version constraint in Chart.yaml
`

Sample Chart.yaml
```
dependencies:
- name: livy
  version: "v2.0.2"
  repository: https://jahstreet.github.io/helm-charts
```

**Comment by naru014** [comment] 2022-06-21 05:31
I know its too late to comment on this. The problem is with using v2.0.2 I think.
I am using it with "2.0.* " and the latest is 2.0.1 I think as thats the version I see getting used in my cluster.

**Comment by jahstreet** [comment] 2022-10-20 07:54
Closing this issue in favour of https://github.com/JahstreetOrg/spark-on-kubernetes-helm/issues/82 within which it (and similar to it) should be resolved, lets continue there.

And thanks for the patience 🙏 .

**Closed as completed by jahstreet** 2022-10-20 07:54 UTC
